version: '3.5'
services:
  console:
    build: .
    command: bash -c "bundle exec ruby bin/rails console"
    volumes:
      - bundle_cache:/bundle
      - .:/myapp
      - "auth_cache:/home/user/.ssh"
    env_file: .env

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec ruby bin/rails server --port 3000 -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - bundle_cache:/bundle
      - .:/myapp
      - "auth_cache:/home/user/.ssh"
    env_file: .env

  auth:
    build: .
    command: bash -c "cp /run/secrets/id_rsa /auth/id_rsa && chmod 600 /auth/id_rsa && ssh-keyscan -t rsa github.com >> /auth/known_hosts"
    volumes:
      - auth_cache:/auth
    secrets:
      - id_rsa

  bundler:
    build: .
    command: bash -c "bundle check || bundle install"
    volumes:
      - bundle_cache:/bundle
      - .:/myapp
      - "auth_cache:/home/user/.ssh"

  guard:
    build: .
    command: bash -c "guard"
    volumes:
      - bundle_cache:/bundle
      - .:/myapp
      - "auth_cache:/home/user/.ssh"

volumes:
  bundle_cache:
  auth_cache:

secrets:
  id_rsa:
    file: ~/.ssh/id_rsa
